### ISSUE TITLE
Is maxent_bryan application available?

### ISSUE THREAD

**Issue by henhans** [TRIQS/tutorials#1]
Dear TRIQS team,

I'm wondering if the pytriqs.applications.maxent_bryan application still available. I'm studying the tutorial "08-Single-orbital_Hubbard_with_CTQMC". It seems there's no maxent_bryan in the pytriqs application. Bellow is the error message:
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-16-1262f852c0f5> in <module>()
----> 1 from pytriqs.applications.maxent_bryan import performMaxent
      2 
      3 # Parameters of the MaxEnt
      4 NOmega = 100
      5 wmin = -10.

ImportError: No module named maxent_bryan

Thank you!
Tsung-Han

**Comment by mferrero** [comment]
Hi!

The maxent code is not available in TRIQS for the moment. I will update the tutorials to remove this part. For the time being, if you want to do some analytical continuations, you will have to use your own codes.

Cheers!

**Comment by henhans** [comment]
I see. Thank you!
Tsung-Han
