### ISSUE TITLE
Python header not found during make (as in #662 issue)

### ISSUE THREAD

**Issue by dmantadakis** [TRIQS/tutorials#10]
Dear All,

I installed the unstable branch and I run into the same problem (Python.h not found) when trying to build a standalone c++ executable using the CMakeLists.txt and arrays.cpp that I found at

https://github.com/TRIQS/tutorials/tree/master/TRIQSPaperExamples/c%2B%2B

The same error occurs when trying to build against the master branch too. Any help would be appreciated.

Best,
Danny

**Comment by Wentzell** [comment]
Hey @dmantadakis 

The tutorials you mention were indeed outdated. I just updated them for triqs 2.0.

Please try again with the updated examples.

**Comment by dmantadakis** [comment]
Dear Nils,
Thanks for the updated examples. I verify that it works for both "master" and "unstable" branch. 
Best, 
Danny

P.S. Note, however, that in the first case (master-branch) I get more warnings. In any case, thanks a lot!
