### ISSUE TITLE
Charge self-consistency tutorial

### ISSUE THREAD

**Issue by katanin** [TRIQS/tutorials#14]
Could you please provide the correct link to the Charge self-consistency tutorial? The one provided in (https://github.com/TRIQS/tutorials/tree/3.1.x/AbinitioDMFT)/04-HubbardI-comparison.ipynb, namely https://flatironinstitute.github.io/solid_dmft/tutorials/Ce2O3_csc_w90/tutorial.html does not work.

**Comment by Wentzell** [comment]
Dear @katanin,

The correct link to the solid dmft tutorial you are looking for is https://triqs.github.io/solid_dmft/tutorials/Ce2O3_csc_w90/tutorial.html
Thank you for pointing out the broken link.

**Comment by Wentzell** [comment]
This was fixed in https://github.com/TRIQS/tutorials/commit/b26aec22d8ecb8eae66d8291c9f14beee7fd6fb5 and https://github.com/TRIQS/tutorials/commit/999dc1572c5f33f813f918814adf9d20720e76c5
